### ISSUE TITLE
Dismount doesn't work in combat

### ISSUE THREAD

**Issue by SurgeMonkeyAU** [bennieboj/BlishHud-Mounts#16]
When in combat, the radial "keybind" disables, making it impossible to dismount using the same key. You can manually dismount if you bind the GW2 Mount/Dismount key seperately.
```
Blish Key binding = X   (Does not work to dismount in combat)
GW2 Mount/Dismount = NumPad 0  (Works to dismount in combat)
```
Video of bug:  https://imgur.com/a/e4STcVo

**Comment by bennieboj** [comment]
[fixed in 1.2.14](https://discord.com/channels/531175899588984842/937111117069701171/949328307105710080)
