### ISSUE TITLE
Radial keybind in action camera mode on dual monitor moves cursor to center of main screen

### ISSUE THREAD

**Issue by dang-nabbit** [bennieboj/BlishHud-Mounts#28]
I have two monitors and play with my game window on the secondary screen. Whenever I'm in action camera mode and use the keybind, my cursor moves to the center of the main screen (making me select one of the two mounts on the right side of the radial, instead of the center).

If I move my game window to the main screen, the cursor moves to the center of the game window instead, causing the correct behavior.

If I turn off "spawn at mouse", the cursor goes to the main screen even if I have action cam off. I guess it's an issue with forcing the cursor to the center of the screen, but using the main screen instead of the one the game window is on.

Here's a video recording of the keybind effect spanning both screens, with action cam on and off for comparison: [Google Drive video](https://drive.google.com/file/d/15dwyT1O17qeVNgDEYSvLTIEaqb39b-9X/view?usp=sharing)
And here's the debug log of the recorded above (in between me turning debug logging on and off): [Google Drive log file](https://drive.google.com/file/d/11v0lK_sIs3Yv_Ulpal_cfX1-3SOwx3_Q/view?usp=sharing)

For now I'm playing with the game on my main screen as a workaround, but I hope you get a chance to look into it. Thanks in advance! :)

**Comment by bennieboj** [comment]
This should be fixed in 1.4.6.
If this is not the case, please comment again to reopen this issue, closing for now.
