### ISSUE TITLE
Move Mount icons

### ISSUE THREAD

**Issue by acer2220** [bennieboj/BlishHud-Mounts#30]
First, love the Module. It would be nice to move the manual icons on the screen and a group. 
Either way great work!

**Comment by bennieboj** [comment]
Hi,
You can move the manual mount icons around if you check the "Enable dragging" checkbox.
![2022-10-10 16_21_37-Blish HUD](https://user-images.githubusercontent.com/4215739/194888209-763c86f8-7788-4938-b92c-6d4da127d591.png)
If you mean something else, please clarify so we have the same understanding.

**Comment by acer2220** [comment]
100% what I was looking for and missed it. Thanks

**Comment by bennieboj** [comment]
Cool, anytime!

**Comment by DaitiDay** [comment]
Maybe a stupid question, but is this still possible? I'm on v1.4.8 and can't find that menu ._.
