### ISSUE TITLE
Tooltips on radial

### ISSUE THREAD

**Issue by yoriaiko** [bennieboj/BlishHud-Mounts#4]
hey o/

Please make tooltips over radial optional.

To me its common to move camera by holding right mouse button and moving mouse. Once I open radial, the tooltip over selected mount popup, and block my RMB till I move my cursor a little (even a single pixel)  after selecting - can't click RMB right instantly after releasing radial button.

Thx for fancy work.

**Comment by bennieboj** [comment]
Thanks for reporting.

Tooltips are disabled on radial in the next version I think.
This is a bug that's on the list already. It's not related to tooltips, but I don't know what is just yet.

We'll look into the bug and try to resolve it.

Also reported by discord user: Melo | Sorarey#7590
Whenever I open up the radial but don't perform an action, (So I simply press my keybind "V" and open up the radial and release in the middle => no action) then I can't use my right mouse key to move the camera. I always have to click right or left a second time so I can move it again. 

Asked Freesnow about it here: https://discord.com/channels/531175899588984842/534492173362528287/946145688151019561

**Comment by bennieboj** [comment]
No feedback, old issue, closing
