### ISSUE TITLE
Radial hotkey ignores modifier keys

### ISSUE THREAD

**Issue by jonchardy** [bennieboj/BlishHud-Mounts#5]
I've got my radial mount hotkey set to Ctrl-Z, and noticed that any press of the Z key causes the radial menu to appear.

I suspect some modifier key checks should be added here:
https://github.com/manlaan/BlishHud-Mounts/blob/main/Module.cs#L388

Love the module!

**Comment by bennieboj** [comment]
will be fixed in #6

**Comment by bennieboj** [comment]
Please update to blishhud version 0.11.7 and module version 1.2.12 and report back.

**Comment by jonchardy** [comment]
Works!
