### ISSUE TITLE
Can't Dismount

### ISSUE THREAD

**Issue by BobotheHutt** [bennieboj/BlishHud-Mounts#50]
Is it possible to add a feature where using the set key bind when already mounted will use the last used mount in-game keybinding and therefor dismount?  So far this module has been wonderful to replace radial mount but I'd love to be able to dismount as well.

**Comment by bennieboj** [comment]
Hi!

This module should do that or I'm wrongly understanding the problem.
Normally when mounting and you're already mounted when pressing the keybind it should dismount.

Can you please do the following:
- Make a screenshot of your mount module and in-game settings?
- Please turn on debug logs in BlishHUD (Settings > Overlay settings > enable debug logging) 
- generate a log (typically found in documents/Guild wars 2/addons/blishhud/logs) in as little steps as possible, add the log file here.

**Comment by BobotheHutt** [comment]
Maybe its the keybind I use = but I have never been able to get it to dismount.

![image](https://github.com/manlaan/BlishHud-Mounts/assets/3207495/05fca4b0-1ec1-427e-90c3-166bf7260351)

**Comment by BobotheHutt** [comment]
A quick look at the logs and I think what I'm seeing is no matter what mount I'm on, its trying to use the F8 key to dismount which is skyscale.  I don't have that on this account but its still set to F8 for my main account.

I swapped around accounts to test some things out.  Looks like it works as long as I don't have any mount keybinds enabled for mounts I don't have.  Settings don't save when I swap accounts but that not a big deal.  I just need to remember to toggle mounts back and forth every time I swap accounts which is not too hard to do.

**Comment by bennieboj** [comment]
That totally makes sense!

I could maybe change it so it always uses raptor or something? If everyone has that mount ofc, idk if it always goes in that order. 
Or order the mount actions to dismount in the likeliness of people having that mount?
I'll think of something and let you know when it's implemented.

**Comment by BobotheHutt** [comment]
Thanks.  I'm even glad with the current work around.  If there is a fix that's easy that would be great but I wouldn't spend too much time on this.  All is good now :)  

I'm going to delete my log since I didn't edit things out.

**Comment by bennieboj** [comment]
This should be fixed in version 1.3.3 which should appear shortly.
Can you confirm please?

**Comment by BobotheHutt** [comment]
Just got the update and it looks to be working.  On my alt account, I left the mounts enabled that I don't have and dismount worked on all the mounts I did have.  I no longer have to disable/reenable mounts as I swap accounts.

Thanks for figuring it out!
