### ISSUE TITLE
Custom action, custom buttons

### ISSUE THREAD

**Issue by yoriaiko** [bennieboj/BlishHud-Mounts#54]
Here is my request, to add more buttons, selectable, optional.

With more and more hard to access buttons, not only novelties, but then mastery buttons, and now combat intense mastery buttons, ez access to them via wheel could be super awesome!

Maybe not fully customizable keypresses with custom icons on many wheels at once like radialmount standalone addon (i mean outside blish launcher), but just few more premade buttons - like with non related icons maybe - as true, the action dont need to be in line with icon and ui name (like i could use rift scanner bind onto warclaw mount button of current version, it would work and none would stop me lol)

Many thx for an update!

**Comment by bennieboj** [comment]
See version 1.4.0 beta on discord.
