### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by Conjurman** [bennieboj/BlishHud-Mounts#55]
Having difficulty setting up mounts. Cannot get center mouse button to map.  Also have matched key mapping same as in game, but radial not woeking.  Is there a more detailed instruction for this module?

**Comment by bennieboj** [comment]
Thanks for the report.
Mouse buttons are not supported for keybinds in general in Blishhud just yet. It's planned but don't expect it soon.
See https://github.com/blish-hud/Blish-HUD/issues/611
