### ISSUE TITLE
Default Mount in sky and water

### ISSUE THREAD

**Issue by alkingshefo** [bennieboj/BlishHud-Mounts#57]
i was thinking of making the default mount similar to land default mount just in the middle and let me access the other radial options instead of forcing me to only use that mount in air/water <3
another thing if possible some option setting for keybinding maybe skyscale different button for combat thing or merge with existing one but i can't think of a good way to make it, still thinking about how.

**Comment by bennieboj** [comment]
Not sure if this fixes any of this, but make sure to check out the beta version here: https://discord.com/channels/531175899588984842/1136363059674357810

**Comment by bennieboj** [comment]
Update: version 1.4.0 is in public release.
This might solve your issue.
