### ISSUE TITLE
Context IsPlayerGlidingOrFalling is inconsistent and dependent or blish hud graphics settings

### ISSUE THREAD

**Issue by DragonHeart996** [bennieboj/BlishHud-Mounts#60]
the gliding/falling detection is very inconsistent and dependent on the main blishud graphics settings. if smooth character position is off, it just flickers wildly. more importantly, it is dependent on the framerate blish is set to. at 90 fps it works fine, but at 60 it can start to flicker while gliding, and at 30fps it often does not detect gliding at all.

**Comment by bennieboj** [comment]
Can you try version 1.4.2 or higher.
Flying detection was improved in 1.4.2 
https://pkgs.blishhud.com/Manlaan.Mounts.html

**Comment by DragonHeart996** [comment]
working better but still iffy at times. particularly it fails after using glider booster on any refresh rate other than match monitor, and is flickering some on 60 fps. monitor is 144 fps.
edit: the glide booster issue also happens on 144 fps, but only a few seconds after the end of the boost, rather than instantly

**Comment by bennieboj** [comment]
Could you test both these bhm files please?

Install them **one at a time** manually, here are the instructions on how to do that:
https://blishhud.com/docs/user/installing-modules/#manually-installing-modules
Don't put them in the modules folder at the same time please :)
If you need any help, please let me know.

[Mounts-release-1.4.7-beta-flying1.zip](https://github.com/bennieboj/BlishHud-Mounts/files/13492230/Mounts-release-1.4.7-beta-flying1.zip)

**Comment by DragonHeart996** [comment]
both work great! threshold 0.1 seems generally more responsive than 0.2, which seems to lag behind at times. only had one occurence of it switching to flying while on stairs with 0.1 (unable to replicate, probably caused by a framerate hitch). 0.2 also occasionally switched back to default context at the apex of glide booster, but thats pretty minor and didnt happen often.

**Comment by bennieboj** [comment]
Glad to hear that! I'll release 1.4.7 later this week! :)
I'll close this issue once it's released.

**Comment by DragonHeart996** [comment]
you still have the usual of it triggering going down stairs when you jump onto them and keep moving w/o stopping, but i understand that its not really avoidable given the data you get from the game, and still better than previous where it triggered on stairs even when you didnt jump

**Comment by bennieboj** [comment]
1.4.7 is released.

I'm closing this for now, if you still have issues, feel free to leave a comment
