### ISSUE TITLE
Queued for out of combat: Raptor not working

### ISSUE THREAD

**Issue by SpyrosPsarras** [bennieboj/BlishHud-Mounts#61]
Hi. 
I am trying to bring back the functionality of this module for my setup but I am failing to do so. I am a developer my self so please let me know if I forgot to mention something and I will provide.
Everything in this module works except the queue out of combat. In the recent update this broke for me, previously this was working like a charm. 
I have enabled the `IsPlayerinCombat` with Default `Disabled`, Center `LastUsed` and all of the other settings enabled. Actually I have tried all possible combination. 
![image](https://github.com/bennieboj/BlishHud-Mounts/assets/13405649/3838eef4-f01a-4c01-90d5-4ce93eb11587)
![image](https://github.com/bennieboj/BlishHud-Mounts/assets/13405649/cf2b3d57-37a7-4825-aeae-fd398cddcab4)
I have enabled also the debug mode for this screen recording so you can validate that the queue is there but not happening. https://youtu.be/o9QMVOuaOtM
I am providing also my settings json https://pastecode.io/s/ub9i98fp

**Comment by bennieboj** [comment]
Hi,
Thanks for the details report.
I'll fix this in 1.4.4, going out as soon as Freesnow hits the publish button on this:
https://github.com/blish-hud/bhud-pkgs/pull/729

**Comment by bennieboj** [comment]
Fixed in 1.4.4.
If something else related to this comes up, leave a comment, but I'm closing this for now.
