### ISSUE TITLE
Dismount when activating user defined radial.

### ISSUE THREAD

**Issue by bolb** [bennieboj/BlishHud-Mounts#62]
Hey,

i think i found a bug with the user defined radial.
if you trigger it mounted, it will also trigger IsPlayerMounted action if "Apply instalty if single" is activated.
if the checkbox isnt checked it works perfect.

**Comment by bennieboj** [comment]
Hi,
Thanks for the report.
Could you please provide a bit more context (screenshot of the general settings, the IsPlayerMounted radial context, the user defined radial context, ..)
https://github.com/bennieboj/BlishHud-Mounts/blob/main/README.md#debugging-option-logging-and-reporting-issues

**Comment by bolb** [comment]
![pressed_y_while_mounted](https://github.com/bennieboj/BlishHud-Mounts/assets/20342644/65d2f4ff-2535-4b16-bf1c-20723038f0b5)
![settings_1](https://github.com/bennieboj/BlishHud-Mounts/assets/20342644/06585621-9d16-4fb8-9755-3cad79c260ac)
![settings_2](https://github.com/bennieboj/BlishHud-Mounts/assets/20342644/6800eab8-11bd-4263-a304-30522c3b056b)
![settings_3](https://github.com/bennieboj/BlishHud-Mounts/assets/20342644/440b7906-7084-4647-baf2-9810d7eba2cd)
![settings_4](https://github.com/bennieboj/BlishHud-Mounts/assets/20342644/d15eed08-8c25-47b0-8096-e14ef242f018)
[blishhud.20231127-172345.log](https://github.com/bennieboj/BlishHud-Mounts/files/13477832/blishhud.20231127-172345.log)

**Comment by bennieboj** [comment]
Issue found, bugfix incoming!
Will comment when the bugfix is live.

**Comment by bennieboj** [comment]
1.4.5 should fix this issue.
Feel free to comment if it doesn't, but for now I'm closing this issue.
