### ISSUE TITLE
radial buttons

### ISSUE THREAD

**Issue by Elminster067** [bennieboj/BlishHud-Mounts#63]
I do not know if this is intended but in order to get the radial buttons to display I have to mount first then dismount then i can chose which mount I want to use, other wise radial button will just blink and I would mount what ever mount is in the mount box first.

**Comment by Elminster067** [comment]
although, come to think of it, it could come in handy, i use a controller (this issue works on keyboard and controller) because of my carpal tunnel and not many hotkeys i can use on it so having it do the above problem could have 2 mounts hotkeyed :P

**Comment by bennieboj** [comment]
Hi,

Could you make 2 screenshots please. Go to radial settings (2nd tab in the module settings).
The make a screenshot of that screen.
It should look kinda like this:
![2024-04-02 19_08_33-Blish HUD](https://github.com/bennieboj/BlishHud-Mounts/assets/4215739/7cae0c47-58ae-409e-821b-6c84c67d4c5c)


Then click on the Edit button next to IsPlayerMounted, then make another screenshot.
It should look kinda like this:
![2024-04-02 19_08_40-Blish HUD](https://github.com/bennieboj/BlishHud-Mounts/assets/4215739/09cfd038-9e3f-446b-b7f1-b24579bb0ddd)


You can just drop screenshots in your comment here :)

**Comment by Elminster067** [comment]
![Screenshot 2024-04-02 133603](https://github.com/bennieboj/BlishHud-Mounts/assets/119313387/f1571557-1d88-4c15-a636-2531e1db6782)
![Screenshot 2024-04-02 133638](https://github.com/bennieboj/BlishHud-Mounts/assets/119313387/1713ed3e-9a05-4f3c-8640-562bb0151a8d)

**Comment by bennieboj** [comment]
Can you turn on "debug logs" and "additional debug data" in BlishHUD:
https://github.com/bennieboj/BlishHud-Mounts/blob/main/README.md#debugging-option-logging-and-reporting-issues

Could you make a screenshot of the "additional debug data" (red text on the screen) when holding down the module hotkey?

And send me some logs?:
- turn on these options
- restart BlishHUD (right click the icon) in-game
- reproduce the issue
- stop BlishHUD (right click exit)
- copy the latest log file in here (Documents\Guild Wars 2\addons\blishhud\logs (or a similar folder inside your Settings folder when running in portable mode).).

**Comment by bennieboj** [comment]
And also a screenshot of your first module tab (general settings)?

**Comment by Elminster067** [comment]
![Screenshot 2024-04-02 144516](https://github.com/bennieboj/BlishHud-Mounts/assets/119313387/1df0d9d6-a18b-4171-bdfc-3053bf8c46a6)

**Comment by Elminster067** [comment]
[blishhud.20240402-134430.log](https://github.com/bennieboj/BlishHud-Mounts/files/14842523/blishhud.20240402-134430.log)
[blishhud.20240402-123640.log](https://github.com/bennieboj/BlishHud-Mounts/files/14842527/blishhud.20240402-123640.log)
the last one is from 1:44 today, i didnt turn on logs at that time, there are others in the folder as well

**Comment by Elminster067** [comment]
and sorry for the delay, had to pick up my kid from school

**Comment by bennieboj** [comment]
No worries, I got time :)

Your keybinds are overlapping (Shift+X for the Unmount action and X for the module keybind).
[Overlapping keybinds are not supported](https://github.com/bennieboj/BlishHud-Mounts/blob/main/README.md#keybinds), that's why they show up red in your screenshot.
You can change the Unmount keybind to anything you want (both in the module settings and in-game.

You can still automatically unmount by configuring the IsPlayerMounted action as in my own screenshot.

**Comment by Elminster067** [comment]
oh, i ran the controls a few times

**Comment by Elminster067** [comment]
it does the same thing both ways i changed it back to x and still doing it

**Comment by Elminster067** [comment]
![Screenshot 2024-04-02 145943](https://github.com/bennieboj/BlishHud-Mounts/assets/119313387/4296f07b-044a-476a-81ba-a9034254f7ce)
before i ran the debuging i changed it back to x, i was just trying to find a work around

**Comment by Elminster067** [comment]
![Screenshot 2024-04-02 150142](https://github.com/bennieboj/BlishHud-Mounts/assets/119313387/ed678805-9d90-4864-aa48-e638fe0c6dcc)

**Comment by Elminster067** [comment]
![Screenshot 2024-04-02 150426](https://github.com/bennieboj/BlishHud-Mounts/assets/119313387/cd38cc59-adc4-48b6-badc-11d12d77ad99)

**Comment by bennieboj** [comment]
Having both set to "X" is also not supported.

Can you try completely separate keybinds? Just pick anything that's not in use, just for testing Maybe the "N" or something?

It doesn't need to be in reach of your hands, normally if the modules functions properly you should be able to do everyting with the 1 single module keybind.

**Comment by Elminster067** [comment]
all the keybinds?

**Comment by bennieboj** [comment]
I meant the module keybind and the Unmount keybind should not be the same.

The purple one in this [picture](https://github.com/bennieboj/BlishHud-Mounts/blob/main/README.md#keybinds) cannot overlap in any way with the Unmount keybind.

**Comment by Elminster067** [comment]
i changed the dismount to N and still doing it

**Comment by Elminster067** [comment]
but no new debug log since 2:55

**Comment by Elminster067** [comment]
I have to go drop my kid off at school for color guard be back in a few

**Comment by bennieboj** [comment]
Could you send me another screenshot of your 1st module settings tab?

Could you make a new log file please with the settings for Unmount set to "N" (both in-game and in the module)?

- restart BlishHUD (right click the icon) in-game
- reproduce the issue (please only hold the "X" key **once**)
- stop BlishHUD (right click exit)
- copy the latest log file in here (Documents\Guild Wars 2\addons\blishhud\logs (or a similar folder inside your Settings folder when running in portable mode).).

**Comment by Elminster067** [comment]
![Screenshot 2024-04-02 154439](https://github.com/bennieboj/BlishHud-Mounts/assets/119313387/48777099-022f-4c6e-a5dd-712ac263df52)

**Comment by Elminster067** [comment]
i do not see a separate space for dismount in game

**Comment by bennieboj** [comment]
You should set the Mount/Dismount action ingame to "N" as well.

**Comment by Elminster067** [comment]
[blishhud.20240402-134430.log](https://github.com/bennieboj/BlishHud-Mounts/files/14842960/blishhud.20240402-134430.log)

**Comment by Elminster067** [comment]
blah changed that, now it works, now i have to change my ps5 setting to n as well

**Comment by Elminster067** [comment]
oh no, i do not it still works on the ps5 controller :P

**Comment by bennieboj** [comment]
You can change all settings as you wish as long as they don't overlap.
I'm happy it works :)

**Comment by Elminster067** [comment]
na, not changing anything else till i get my other mounts, need to get used to the controller, always used keyboard mouse and now it is to painful to use both for anything longer than an hour
