### ISSUE TITLE
Feature Request: Emotes

### ISSUE THREAD

**Issue by AdamArcane** [bennieboj/BlishHud-Mounts#65]
It would be cool to be able to have a radial wheel or icon bar for emotes

**Comment by bennieboj** [comment]
Hi, I believe this module has a radial for emotes: https://blishhud.com/modules/?module=xyz.f3l1x.blishemotes

Does this help?

**Comment by AdamArcane** [comment]
I didn't even know that module existed. I'll check it out. Thank you so
much!

**Comment by bennieboj** [comment]
Great! They are using the same or similar radial code. 
I'll close this issue then, if you have more questions feel free to reopen this ticket or ask in [discord](https://discord.gg/jZ37WfsKxR)!
