### ISSUE TITLE
Radial menu captures hotkey when pressed, can't be used in button combinations anymore

### ISSUE THREAD

**Issue by imadesoup** [bennieboj/BlishHud-Mounts#66]
I use Left Shift as my hotkey for the radial mount menu. I used to be able to still use, for example, LShift+Win+S to capture screengrabs on OS-level, or LShift+H to open the Wizard's Vault UI.

After a recent change, the hotkey selected for the radial menu (no matter which one, tested with multiple) is no longer recognized by other software - even the OS. It opens the mounts radial menu just fine, but while that's active, I can no longer press H to open Wizard's Vault, nor can I press Win+S to take an OS-level screenshot while (it just opens the start menu now).

If I change the hotkey in the module settings, I instantly get back the expected functionality of the previous key, but lose that of whatever is assigned as the new hotkey.

Was some sort of exclusivity to the hotkey introduced in a recent update? I was previously able to work with the module instead of around it, but that seems to no longer be the case.

Windows 10
Mounts version 1.4.11

**Comment by bennieboj** [comment]
Hi,
This has recently changed in 1.4.11, sorry for the regression.
I released version 1.4.12 in the meantime to make this configurable, but it's still awaiting review.

If you want to [manually install](https://blishhud.com/docs/user/installing-modules/#manually-installing-modules) version 1.4.12 you can find it here: https://github.com/blish-hud/bhud-modules/releases/download/manlaan.mounts_v1.4.12/Manlaan.Mounts-1.4.12.bhm

**Comment by imadesoup** [comment]
Gotcha, thanks for the quick reply! 
I'm in no rush, I can happily wait for the new version :)

Really love this mod, yall are doing a great job!

**Comment by bennieboj** [comment]
Closed this issue, if it for some reason doesn't work then feel free to comment again.
