### ISSUE TITLE
Ground targeting only works correctly when setting to FastWithRangeIndicator

### ISSUE THREAD

**Issue by speedyconzales** [bennieboj/BlishHud-Mounts#68]
I thought you have to set this to the exact value of your in-game settings. but It does only work correctly and lets me place the target on the ground when set to this specific value. So I don't know why this setting is there in the first place if only one value seems to be the correct one

**Comment by bennieboj** [comment]
Which other setting are your trying to use? 

Can you provide some screenshots of your settings (in-game and in the module settings).

**Comment by speedyconzales** [comment]
I can choose whatever I want for in-game. Usually using "instant" 
![image](https://github.com/user-attachments/assets/0b5a0a0a-bc9d-4bc8-9937-a3f755e7b9c3)

setting it in the module settings to any other value than this shown in the screenshot, does lead to the ground target to be place immediately on mouse position. only this setting allows me to choose the position while moving the mouse afterwards
![image](https://github.com/user-attachments/assets/c49e4b34-beaa-425d-98cd-da19ccd6012d)

**Comment by bennieboj** [comment]
Provide full steps, showing ALL your settings and enable all this debug settings, give me a log and video: 
https://github.com/bennieboj/BlishHud-Mounts/blob/main/README.md#debugging-option-logging-and-reporting-issues

**Comment by bennieboj** [comment]
For ground targeting "instant" the activation is postponed till the next mouse click:

https://github.com/bennieboj/BlishHud-Mounts/blob/main/README.md#ground-target-actions

You can display the state via settings related to the [info panel](https://github.com/bennieboj/BlishHud-Mounts/blob/main/README.md#info-panel).

Feel free to reopen this issue if you need more help.
